# Generated by Django 3.1.7 on 2021-02-22 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField(unique=True)),
                ('source', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('start_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_timestamp', models.DateTimeField(null=True)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rates.rate')),
            ],
        ),
    ]
