# Generated by Django 3.1.7 on 2021-02-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_rate_begin', models.TimeField()),
                ('standard_rate_end', models.TimeField()),
                ('standard_standing_charge', models.IntegerField()),
                ('standard_minute_charge', models.IntegerField()),
                ('reduced_rate_begin', models.TimeField()),
                ('reduced_rate_end', models.TimeField()),
                ('reduced_standing_charge', models.IntegerField()),
                ('reduced_minute_charge', models.IntegerField()),
            ],
        ),
    ]
